language: android

cache: false

sudo: true

env:
    global:
        - ANDROID_API_LEVEL=28
        - ANDROID_BUILD_TOOLS_VERSION=28.0.2
        - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
    components:
        - tools
        - platform-tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL

before_install:
    - yes | sdkmanager "platforms;android-28"

script:
    - ./gradlew clean build --info --stacktrace
